environment:
  my_version_number: 1.0.4
  application_name: Swerver
  project_name: Swerver

version: $(my_version_number).{build}

skip_tags: true

configuration: Release

before_build:
  - ps: nuget restore -Verbosity quiet

build:
  publish_nuget: true
  verbosity: minimal
  project: $(project_name).sln

for:
  - branches:
      only:
        - master

    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '$(my_version_number)'
      package_version: '$(my_version_number)'
      assembly_version: '$(my_version_number)'
      file_version: '$(my_version_number)'
      informational_version: '$(my_version_number)'

    deploy:
      - provider: NuGet
        api_key:
          secure: dvBoUwBIXmJhZm9jD5jxnU5FjrHji0KMbTMxgui4jLBnUbFUkBoDN81yuhevoOFo
        artifact: /.*(\.|\.s)nupkg/

      - provider: NuGet
        api_key:
          secure: t+q9dcBPFxzZdmdGxIahNaP0GHE90XdbEHHVMrmroJpFSCkM3d3tQ2QOtPYQTBpu
        server: https://nuget.pkg.github.com/TheSwerik/index.json
        artifact: /.*(\.|\.s)nupkg/
        username: TheSwerik